'''Regardless of my own initial adjustments to the feature names in "format_dataset.py",
the feature names provided in the csv files do not all correspond with the feature names
provided by the CICFlowMeter.'''

renaming_dict = {
    'dst_port':'destination_port',
    'tot_fwd_pkts': 'total_fwd_pkts',
    'tot_bwd_pkts': 'total_bwd_pkts',
    'totlen_fwd_pkts': 'total_len_of_fwd_pkts',
    'totlen_bwd_pkts': 'total_len_of_bwd_pkts',
    'fwd_pkt_len_max': 'fwd_pkt_len_max',
    'fwd_pkt_len_min': 'fwd_pkt_len_min',
    'fwd_pkt_len_mean': 'fwd_pkt_len_mean',
    'fwd_pkt_len_std': 'fwd_pkt_len_std',
    'bwd_pkt_len_max': 'bwd_pkt_len_max',
    'bwd_pkt_len_min': 'bwd_pkt_len_min',
    'bwd_pkt_len_mean': 'bwd_pkt_len_mean',
    'bwd_pkt_len_std': 'bwd_pkt_len_std',
    'flow_byts/s': 'flow_bytes/s',
    'flow_pkts/s': 'flow_pkts/s',
    'fwd_iat_tot': 'fwd_iat_total',
    'bwd_iat_tot': 'bwd_iat_total',
    'fwd_header_len': 'fwd_header_len',
    'bwd_header_len': 'bwd_header_len',
    'fwd_pkts/s': 'fwd_pkts/s',
    'bwd_pkts/s': 'bwd_pkts/s',
    'pkt_len_min': 'min_pkt_len',
    'pkt_len_max': 'max_pkt_len',
    'pkt_len_mean': 'pkt_len_mean',
    'pkt_len_std': 'pkt_len_std',
    'pkt_len_var': 'pkt_len_variance',
    'fin_flag_cnt': 'fin_flag_count',
    'syn_flag_cnt': 'syn_flag_count',
    'psh_flag_cnt': 'psh_flag_count',
    'ack_flag_cnt': 'ack_flag_count',
    'urg_flag_cnt': 'urg_flag_count',
    'pkt_size_avg': 'avg_pkt_size',
    'fwd_byts/b_avg': 'fwd_avg_bytes/bulk',
    'fwd_pkts/b_avg': 'fwd_avg_pkts/bulk',
    'fwd_blk_rate_avg': 'fwd_avg_bulk_rate',
    'bwd_byts/b_avg': 'bwd_avg_bytes/bulk',
    'bwd_pkts/b_avg': 'bwd_avg_pkts/bulk',
    'bwd_blk_rate_avg': 'bwd_avg_bulk_rate',
    'subflow_fwd_pkts': 'subflow_fwd_pkts',
    'subflow_fwd_byts': 'subflow_fwd_bytes',
    'subflow_bwd_pkts': 'subflow_bwd_pkts',
    'subflow_bwd_byts': 'subflow_bwd_bytes',
    'init_fwd_win_byts': 'init_win_bytes_fwd',
    'init_bwd_win_byts': 'init_win_bytes_bwd',
    'Label': 'label'}